name: Build
on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  cloud-login:
    uses: "rajatjindal/actions/.github/workflows/auth.yml@fix-auth2"
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}
    with:
      fermyon_deployment_env: developer-docs-preview

  preview:
    runs-on: "ubuntu-latest"
    needs: [cloud-login]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved cloud token
        uses: actions/download-artifact@v3
        with:
          name: developer-docs-preview.json
          path: ${{ env.GITHUB_WORKSPACE }}

      - run: echo "workspace is $GITHUB_WORKSPACE"
      - run: pwd && ls -ltr $GITHUB_WORKSPACE
      - name: Deploy preview on cloud
        uses: rajatjindal/some-action@main
        with:
          github_token: $GITHUB_TOKEN
          fermyon_token_file: "${GITHUB_WORKSPACE}/developer-docs-preview.json"

  cleanup: 
    runs-on: ubuntu-latest
    needs: [preview]
    if: always()
    steps:
    - uses: geekyeggo/delete-artifact@v2
      if: always()
      with:
        name: developer-docs-preview.json