name: Cleanup Preview
on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  cleanup-preview:
    if: ${{ github.repository_owner == 'fermyon' && github.event.payload.action === 'closed'}}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3

      - name: Undeploy preview from cloud
        uses: rajatjindal/fermyon-cloud/pr-preview@main
        with:
          fermyon_token: ${{ secrets.FERMYON_CLOUD_TOKEN }}
          undeploy: true
