name: Deploy preview of developer docs
on:
  pull_request:
    branches: [main]

jobs:
  cloud-login:
    uses: "rajatjindal/actions/.github/workflows/auth.yml@fix-auth2"
    with:
      fermyon_deployment_env: developer-docs-preview
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}        

  deploy-preview:
    runs-on: "ubuntu-latest"
    needs: cloud-login
    steps:
      - uses: actions/checkout@v3

      - run: pwd && ls -ltr

      - name: Retrieve saved cloud token
        uses: actions/download-artifact@v3
        with:
          name: developer-docs-preview.json
          path: ${{ env.GITHUB_WORKSPACE }}

      - name: Deploy preview on cloud
        uses: rajatjindal/fermyon-cloud-preview@v0.0.7
        with:
          fermyon_deployment_env: developer-docs-preview

  cleanup: 
    runs-on: ubuntu-latest
    needs: [deploy-preview]
    if: always()
    steps:
    - uses: geekyeggo/delete-artifact@v2
      if: always()
      with:
        name: developer-docs-preview.json