name: Deploy preview of developer docs
on:
  pull_request:
    branches: [main]

jobs: 
  deploy-preview:
    runs-on: "ubuntu-latest"
    steps:
      - name: setup spin pls
        uses: rajatjindal/setup-spin@main
        with:
          version: v0.8.0
  
  deploy-preview-2:
    runs-on: "windows-latest"
    steps:
      - name: setup spin pls
        uses: rajatjindal/setup-spin@main
        with:
          version: v0.8.0

  deploy-preview-3:
    runs-on: "macos-latest"
    steps:
      - name: setup spin pls
        uses: rajatjindal/setup-spin@main
        with:
          version: v0.8.0