name: Deploy preview of developer docs
on:
  pull_request:
    branches: [main]

jobs:
  cloud-login:
    uses: "fermyon/actions/.github/workflows/auth.yml@main"
    secrets:
      gh_username: ${{ secrets.DEV_DOCS_PREVIEW_GH_USERNAME }}
      gh_password: ${{ secrets.DEV_DOCS_PREVIEW_GH_PASSWORD }}
      gh_totp_secret: ${{ secrets.DEV_DOCS_PREVIEW_GH_TOTP_SECRET }}
    inputs:
      fermyon_deployment_env: developer-docs-preview

  preview:
    runs-on: "ubuntu-latest"
    needs: [build, cloud-login]
    steps:
      - uses: actions/checkout@v3

      - name: Install spin
        uses: engineerd/configurator@v0.0.8
        with:
          name: "spin"
          url: "https://github.com/fermyon/spin/releases/download/v0.8.0/spin-v0.8.0-linux-amd64.tar.gz"
          pathInArchive: "spin"

      - name: Deploy preview on cloud
        uses: rajatjindal/fermyon-cloud-preview@v0.0.3
        with:
          fermyon_deployment_env: developer-docs-preview